import { BaseEntity } from './../../shared';
import {Comuna} from '../comuna';
import {SistemaAgua} from '../sistema-agua';
import {Situacao} from '../situacao';

export class IndicadorProducao implements BaseEntity {
    constructor(
        public id?: number,
        public idUsuario?: number,
        public dtLancamento?: any,
        public dtUltimaAlteracao?: any,
        public qtdPopulacaoCobertaInfraestrutura?: number,
        public qtdFontanariosChafarisesOperacionais?: number,
        public qtdMediaHorasDistribuicaoDiaria?: number,
        public qtdMediaHorasParagem?: number,
        public qtdMediaHorasInterrupcaoFaltaEnergia?: number,
        public qtdVolumeAguaCaptada?: number,
        public qtdVolumeAguaTratada?: number,
        public qtdVolumeAguaDistribuida?: number,
        public qtdConsumoEnergia?: number,
        public qtdConsumoCombustivel?: number,
        public qtdConsumoHipocloritroCalcio?: number,
        public qtdConsumoSulfatoAluminio?: number,
        public qtdConsumoHidroxidoCalcio?: number,
        public qtdReparoCaptacaoEtas?: number,
        public qtdReparoAdutoras?: number,
        public qtdReparoRedeDistribuicao?: number,
        public qtdReparoRamais?: number,
        public qtdManutencaoCurativa?: number,
        public qtdManutencaoPreventiva?: number,
        public qtdManutencaoVerificadoSolicitado?: number,
        public qtdReservatorioLavado?: number,
        public qtdFuncionarios?: number,
        public qtdFuncionariosEfectivos?: number,
        public qtdFuncionariosContratados?: number,
        public qtdFuncionariosOutrasEntidades?: number,
        public qtdNovasLigacoesNovosContratos?: number,
        public qtdNovasLigacoesDomesticasNovosContratos?: number,
        public qtdLigacoesIlegaisRegularizadas?: number,
        public qtdLigacoesFechadas?: number,
        public qtdCortes?: number,
        public qtdReligacoes?: number,
        public qtdLigacoesActivas?: number,
        public qtdLigacoesDomesticasActivas?: number,
        public qtdLigacoesFacturadasBaseLeiturasReais?: number,
        public qtdLigacoesFacturadasBaseEstimativasAvenca?: number,
        public qtdVolumeAguaFacturada?: number,
        public qtdVolumeTotalFacturadaLigacoesDomesticas?: number,
        public qtdVolumeFacturadoBaseLeituraReais?: number,
        public vlrTotalFacturado?: number,
        public vlrFacturasCanceladasNotasCreditos?: number,
        public vlrRealFacturado?: number,
        public vlrTotalCobrado?: number,
        public qtdReclamacoes?: number,
        public qtdReclamacoesRespondidasMenorIgualCincoDias?: number,
        public qtdReclamacoesRespondidasMaisCincoMenosVinteDias?: number,
        public qtdReclamacoesRespondidasMaiorIgualVinteDias?: number,
        public vlrCustoPessoal?: number,
        public vlrCustoFse?: number,
        public vlrCustoEnergia?: number,
        public vlrCustoManutencao?: number,
        public vlrCustoReagentes?: number,
        public vlrCustoDestinoFinalLamas?: number,
        public vlrCustoOperacionaisOpex?: number,
        public vlrCustoAmortizaAnualInvestOpCapex?: number,
        public vlrCustoTotaisCapexOpex?: number,
        public qtdCaptacoes?: number,
        public qtdEtas?: number,
        public qtdReservatorios?: number,
        public qtdEstacoesElevatorias?: number,
        public qtdComprimentoAdutoras?: number,
        public qtdComprimentoRedes?: number,
        public qtdComprimentoRamais?: number,
        public qtdAcoesFormacaoMoPlaneadas?: number,
        public qtdAcoesFormacaoMmsPlaneadas?: number,
        public qtdAcoesFormacaoCmpPlaneadas?: number,
        public qtdAcoesFormacaoSoftwareFornecidosPlanejadas?: number,
        public qtdAcoesFormacaoMoRealizadas?: number,
        public qtdAcoesFormacaoMmsRealizadas?: number,
        public qtdAcoesFormacaoCmpRealizadas?: number,
        public qtdAcoesFormacaoSoftwareFornecidosRealizadas?: number,
        public qtdAcoesFormacaoRealizadas?: number,
        public qtdManuaisMoPrevistos?: number,
        public qtdManuaisMmsPrevistos?: number,
        public qtdManuaisCmpPrevistos?: number,
        public qtdManuaisPrevistos?: number,
        public qtdAcoesManuaisMoRealizadas?: number,
        public qtdManuaisMmsRealizadas?: number,
        public qtdManuaisCmpRealizadas?: number,
        public qtdManuaisRealizados?: number,
        public idSituacaoId?: Situacao,
        public idSistemaAguaId?: SistemaAgua,
        public idComunaId?: Comuna,
    ) {
    }
}
